### PR TITLE
Full screen image of the speaker is shown by tap on the speaker page …

### PR DESCRIPTION
**Pull request by vladbilyk**
…(#48)

### CODE REVIEW

**Comment by pfedotovsky** [comment]
Please change Pull Request to DotNetRu:develop branch

**Comment by vladbilyk** [comment]
I've switched PR to dev branch :)

**Comment by pfedotovsky** [comment]
@vladbilyk looks good, thank you!
Have you tried to run it on iOS?

**Comment by vladbilyk** [comment]
Yep! It works on iOS simulator :)

**Pull request merged**
